Repository hms-dbmi/pic-sure-search-prototype, pull requests merged in 2023-10, with the labels that each got.

#19 [ALS-5000] Resolve High Security Finding log4j dependency
  tagging/pom.xml
Labels: enhancement

#20 [ALS-5000] Resolve High Security Finding log4j dependency (#19)
  tagging/pom.xml
Labels: ignore-for-release

#21 [ALS-5018] Add fence-mapping check
  tagging/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/TagSearchResource.java
  tagging/src/test/java/edu/harvard/hms/dbmi/avillach/hpds/TagSearchResourceTest.java
Labels: bug
